#!/usr/bin/env zsh

script_dir="${0:a:h}"
source "$script_dir/utils.zsh"
homesrc_dir="$script_dir/../home"

opt_dry=0
opt_dst=$HOME
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry)
            opt_dry=1
            shift
            ;;
        --dst)
            if (( $# < 2 )); then
                echo "missing value for --dst" >&2
                exit 1
            fi
            opt_dst=$2
            shift 2
            ;;
        *)
            echo "unknown option: $1"
            exit 1
            ;;
    esac
done

cmds=()
function conf() {
    local src="$homesrc_dir/$1"
    local dst="$opt_dst/$2"

    echo "$1\n  -> $dst"
    cmds+=("\\mkdir -p $(dirname $dst) && \\rsync -a $src $dst")
}

function gen() {
    local gen_exe=$1
    local gen_cmd="$1 $2"
    local dst="$opt_dst/$3"

    if (( ! $+commands[$gen_exe] )); then
        color red "missing gen exe: $gen_exe"
        color red "  $gen_cmd"
        return
    fi

    echo "> $gen_cmd\n  -> $dst"
    cmds+=("\\mkdir -p $(dirname $dst) && $gen_cmd > $dst")
}

function block() {
    local marker_text=$1
    local block_file=$2
    local destination="$opt_dst/$3"

    cmds+=("ensure_block ${(q)marker_text} ${(q)block_file} ${(q)destination}")
}

source "$script_dir/manifest.zsh"

for cmd in "${cmds[@]}"; do
    if ((opt_dry)); then
        echo "$cmd"
    else
        eval "$cmd"
    fi
done
